#!/usr/bin/env bash
# needs community/pacman-contrib and aur/checkupdates-aur

arch=$(checkupdates | wc -l)
packages=$(checkupdates)

text="$arch"
# tooltip="$packages"
# echo "${message//[0-9]/X}"
# tooltip="$(echo "$output" | sed -z 's/\n/\\n/g')"
tooltip="$(echo "$packages" | grep . | sed -z 's/\n/\\n/g')"

echo "{\"text\": \"$text\", \"tooltip\": \"$tooltip\"}"
